### ISSUE TITLE
Further instructions for documentation and video

### ISSUE THREAD

**Issue by zanfee** [philippabele/angular-contact-with-pytorch#21]
Hello @philippabele,

I'm in the process of wrapping up the project and wanted to touch base on a couple of points:

Documentation: Are there any additional guidelines or specific formats for the documentation? Any advice on what to focus on would be really helpful.

60-Second Video: Are there specific requirements regarding the format or content of the video?

As a heads up, I have 3 exams this week so my time is quite tight. Any crucial points or advice to streamline my work on the project would be much appreciated.

Thanks in advance!

**Comment by philippabele** [comment]
See the following project as a reference in quality:

https://github.com/philippabele/ball-bearings-with-quarkus

https://github.com/philippabele/nursing-home-volunteer

**Comment by philippabele** [comment]
See the following project as a reference in quality:

https://github.com/philippabele/ball-bearings-with-quarkus

https://github.com/philippabele/nursing-home-volunteer

Focus on a well written read.me as well as the LaTeX documentation.
